#!/bin/bash

unset CC CXX CC_FOR_BUILD CXX_FOR_BUILD

export PATH="/c/ProgramData/chocolatey/lib/ninja/tools:$PATH"

echo ">> Building and testing cffi..."

for luaver in ${LUA_VERSIONS}; do
    mkdir -p build-${luaver}
    cd build-${luaver}

    cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat' amd64 '&&' \
    meson .. -Dlua_version=vendor -Dlibffi=vendor -Ddeps_dir=deps-${luaver} ${margs} '&&' \
    ninja all '&&' ninja test || exit 1

    cd ..
done

exit 0
