#!/bin/sh

SAMU_REPO="https://github.com/michaelforney/samurai"
SAMU_VER=1.2

mkdir -p host_tools || exit 1
host_path="$(pwd)/host_tools"

echo ">> Fetching samurai..."

wget "${SAMU_REPO}/archive/${SAMU_VER}.tar.gz" || exit 1

echo ">> Unpacking samurai..."

tar xf ${SAMU_VER}.tar.gz || exit 1

echo ">> Building samurai..."

cd samurai-${SAMU_VER} || exit 1
make -j4 || exit 1

echo ">> Installing samurai..."

cp samu ${host_path} || exit 1

echo ">> Installed samurai."

exit 0
