#!/bin/sh

expected_triplet=$TARGET

if [ -z "$expected_triplet" ]; then
    echo "ERROR: target triplet not provided!"
    exit 1
fi

ensure_tool() {
    command -v "$1" > /dev/null
    if [ $? -ne 0 ]; then
        echo "ERROR: Missing tool: $1"
        exit 1
    fi
}

echo ">> Checking tools..."

ensure_tool gcc
ensure_tool g++
ensure_tool clang
ensure_tool clang++
ensure_tool git
ensure_tool tar
ensure_tool wget
ensure_tool make

mkdir -p host_tools

echo ">> Installing meson..."

if [ -n "$(command -v pip3)" ]; then
    sudo pip3 install meson
elif [ -n "$(command -v pip)" ]; then
    sudo pip install meson
else
    echo "ERROR: pip not found"
    exit 1
fi

echo ">> Getting libffi..."

wget "https://ftp.octaforge.org/q66/random/libffi.tar.gz" || exit 1
tar xf libffi.tar.gz || exit 1

echo ">> Getting lua..."

for luaver in ${LUA_VERSIONS}; do
    wget "https://www.lua.org/ftp/lua-${luaver}.tar.gz" || exit 1
    tar xf lua-${luaver}.tar.gz || exit 1
done

if [ "$(uname -s)" != "Linux" ]; then
    exit 0
fi

current_triplet=`gcc -dumpmachine`

if [ -z "$current_triplet" ]; then
    echo "ERROR: Native compiler not present!"
    exit 1
fi

if [ "$expected_triplet" = "$current_triplet" ]; then
    echo "ERROR: Not cross-compiling, done..."
    exit 0
fi

echo ">> Installing toolchain..."

sudo apt-get update || exit 1
sudo apt-get install qemu-user gcc-${expected_triplet} g++-${expected_triplet}

exit $?
